[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_FLAGS = "--prefer-offline --no-audit --no-fund"
  CI = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200