[build]
  command = "npm run build:netlify"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_FLAGS = "--prefer-offline"
  CI = "true"
  npm_config_arch = "x64"
  npm_config_platform = "linux"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200